version: '3'
services:
  akseleran-notifier:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: akseleran-notifier
    container_name: akseleran-notifier
    restart: unless-stopped
    volumes:
      - ./.env:/app/.env